// Bakes public/* into api/page.js so the page function has ZERO runtime
// filesystem or query-string dependencies. Run after editing anything in
// public/:  node build-page.js   (from this directory)
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const FILES = ["index.html", "styles.css", "app.js", "format.js"];
const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
};

const embedded = {};
for (const f of FILES) {
  embedded[f] = readFileSync(join(dir, "public", f), "utf8");
}

const out = `// GENERATED by build-page.js — do not edit. Edit public/* then re-run it.
const MIME = ${JSON.stringify(MIME)};
const BODY = {
${Object.entries(embedded)
  .map(([f, body]) => `  ${JSON.stringify(f)}: ${JSON.stringify(body)},`)
  .join("\n")}
};
const CACHE = {
  "index.html": "public, s-maxage=30, stale-while-revalidate=60",
  "styles.css": "public, s-maxage=86400, immutable",
  "app.js": "public, s-maxage=86400, immutable",
  "format.js": "public, s-maxage=86400, immutable",
};
// Only these 4 names are ever servable — anything else 404s.
const BY_PATH = {
  "/": "index.html",
  "/index.html": "index.html",
  "/styles.css": "styles.css",
  "/app.js": "app.js",
  "/format.js": "format.js",
};
function pick(req) {
  try {
    const u = new URL(req.url || "/", "http://x");
    const f = u.searchParams.get("f");
    if (f && BODY[f]) return f;
    const p = BY_PATH[u.pathname];
    if (p) return p;
  } catch {}
  return null;
}
export default function handler(req, res) {
  const file = pick(req);
  if (!file) {
    res.status(404).send("unknown page asset");
    return;
  }
  const ext = file.slice(file.lastIndexOf("."));
  res.setHeader("Content-Type", MIME[ext]);
  res.setHeader("Cache-Control", CACHE[file]);
  res.status(200).send(BODY[file]);
}
`;

writeFileSync(join(dir, "api", "page.js"), out);
console.log(`baked ${FILES.length} files into api/page.js`);
